export interface Person {
  givenName: string;
  surName: string;
  age: number;
  email: string;
  address: string;
}

export interface EPerson {
  givenName: string;
  surName: string;
  age: string;
  email: string;
  education: string;
}
export const ManyPerson: EPerson[] = [
  {
    givenName: 'Isabella',
    surName: 'Lopez',
    age: '29',
    email: 'isabellalopez77@hotmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Eric',
    surName: 'Morgan',
    age: '41',
    email: 'ericmorgan@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Emma',
    surName: 'Taylor',
    age: '52',
    email: 'emmaltaylor@ymail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Jeremy',
    surName: 'Sanders',
    age: '53',
    email: 'jeremy.michael.sanders@rocketmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Melissa',
    surName: 'Miller',
    age: '55',
    email: 'melissamiller@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Jessica',
    surName: 'Brooks',
    age: '74',
    email: 'jessica.brooks@rocketmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Amelia',
    surName: 'Rodriguez',
    age: '27',
    email: 'amelia.r.rodriguez30@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Julian',
    surName: 'Jones',
    age: '67',
    email: 'julian.wayne.jones40@live.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Alexander',
    surName: 'Davis',
    age: '71',
    email: 'alexanderadavis@gmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Dylan',
    surName: 'Phillips',
    age: '42',
    email: 'dylanphillips@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'John',
    surName: 'Perez',
    age: '26',
    email: 'jperez@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Nathan',
    surName: 'Bailey',
    age: '45',
    email: 'n_l28@live.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Erin',
    surName: 'Taylor',
    age: '42',
    email: 'e.taylor98@ymail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Layla',
    surName: 'Alexander',
    age: '36',
    email: 'laylaalexander@live.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Eric',
    surName: 'Bailey',
    age: '55',
    email: 'e.r.bailey1@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Henry',
    surName: 'Griffin',
    age: '75',
    email: 'h_griffin@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Claire',
    surName: 'Anderson',
    age: '34',
    email: 'c_a_anderson@gmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Alexandra',
    surName: 'Hernandez',
    age: '35',
    email: 'alexandra@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Christina',
    surName: 'Williams',
    age: '49',
    email: 'c_l_williams64@yahoo.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Austin',
    surName: 'Wright',
    age: '58',
    email: 'austinrwright45@gmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Steven',
    surName: 'Foster',
    age: '42',
    email: 'stevenfoster22@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Grace',
    surName: 'Taylor',
    age: '47',
    email: 'g_taylor86@rocketmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Audrey',
    surName: 'Baker',
    age: '50',
    email: 'a.baker@ymail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Samuel',
    surName: 'Gray',
    age: '53',
    email: 'samuel_eugene@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Brian',
    surName: 'Martinez',
    age: '47',
    email: 'brianmartinez@rocketmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Nicholas',
    surName: 'Stewart',
    age: '50',
    email: 'nicholas_stewart@live.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Andrew',
    surName: 'Parker',
    age: '75',
    email: 'andrew.parker@ymail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Patrick',
    surName: 'Diaz',
    age: '42',
    email: 'patrick.a.diaz@yahoo.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Jack',
    surName: 'Hall',
    age: '45',
    email: 'jackhall@rocketmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Theodore',
    surName: 'Butler',
    age: '43',
    email: 't_butler@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'William',
    surName: 'Mitchell',
    age: '58',
    email: 'w_mitchell@outlook.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Alexandra',
    surName: 'James',
    age: '57',
    email: 'a.james@hotmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Sarah',
    surName: 'Scott',
    age: '49',
    email: 'sarahsscott@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Ava',
    surName: 'Young',
    age: '32',
    email: 'avamyoung@live.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Ryan',
    surName: 'Turner',
    age: '40',
    email: 'r_turner@live.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Eleanor',
    surName: 'Hall',
    age: '49',
    email: 'eleanor_m_hall63@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Aaron',
    surName: 'Brooks',
    age: '70',
    email: 'abrooks33@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Aubrey',
    surName: 'Scott',
    age: '49',
    email: 'a.r.scott@hotmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Jonathan',
    surName: 'Wood',
    age: '67',
    email: 'jonathan_scott_wood@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Emily',
    surName: 'Richardson',
    age: '66',
    email: 'emily_j_richardson@aol.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Amelia',
    surName: 'Washington',
    age: '59',
    email: 'amelia.washington@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Haley',
    surName: 'Long',
    age: '54',
    email: 'h.long@yahoo.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Samantha',
    surName: 'Evans',
    age: '35',
    email: 'samantha.evans54@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Ryan',
    surName: 'Bennett',
    age: '39',
    email: 'rrbennett@hotmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Mark',
    surName: 'Walker',
    age: '54',
    email: 'm.j.walker@rocketmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Isabella',
    surName: 'Rivera',
    age: '63',
    email: 'i.rivera@ymail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Zachary',
    surName: 'Peterson',
    age: '42',
    email: 'z.j@aol.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Kyle',
    surName: 'Harris',
    age: '71',
    email: 'kyle_harris25@rocketmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Emma',
    surName: 'Ross',
    age: '61',
    email: 'elross21@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Charles',
    surName: 'Green',
    age: '71',
    email: 'charlesdgreen@hotmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Sean',
    surName: 'Morgan',
    age: '67',
    email: 's.morgan19@hotmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Brian',
    surName: 'Jackson',
    age: '45',
    email: 'b.j@yahoo.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'William',
    surName: 'Rodriguez',
    age: '73',
    email: 'william_rodriguez@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Charles',
    surName: 'Parker',
    age: '26',
    email: 'c.f5@rocketmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Audrey',
    surName: 'Rivera',
    age: '18',
    email: 'arivera@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Benjamin',
    surName: 'Miller',
    age: '77',
    email: 'b.miller@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Timothy',
    surName: 'Cox',
    age: '49',
    email: 't.cox14@hotmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Kimberly',
    surName: 'Bryant',
    age: '28',
    email: 'k.bryant@yahoo.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Isaac',
    surName: 'Morris',
    age: '34',
    email: 'isaacmorris93@yahoo.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Danielle',
    surName: 'Lopez',
    age: '27',
    email: 'd.l.lopez@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Samuel',
    surName: 'Hernandez',
    age: '44',
    email: 's.hernandez@outlook.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Kayla',
    surName: 'Gray',
    age: '42',
    email: 'k_r95@gmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Melissa',
    surName: 'Hill',
    age: '55',
    email: 'mfhill@hotmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Brandon',
    surName: 'Walker',
    age: '41',
    email: 'brandon_j_walker@outlook.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Sophia',
    surName: 'Anderson',
    age: '53',
    email: 's_anderson@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Theodore',
    surName: 'Harris',
    age: '24',
    email: 'tharris19@gmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Christina',
    surName: 'Murphy',
    age: '76',
    email: 'christinamurphy@outlook.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Layla',
    surName: 'Powell',
    age: '72',
    email: 'laylakpowell45@rocketmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Oliver',
    surName: 'Powell',
    age: '76',
    email: 'o.powell@hotmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Tiffany',
    surName: 'Parker',
    age: '59',
    email: 'tmparker@rocketmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Daniel',
    surName: 'Flores',
    age: '57',
    email: 'd.flores@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Brandon',
    surName: 'Simmons',
    age: '23',
    email: 'brandon@yahoo.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Sebastian',
    surName: 'Brooks',
    age: '67',
    email: 's.brooks@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Joshua',
    surName: 'Patterson',
    age: '46',
    email: 'joshuajosephpatterson@outlook.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Robert',
    surName: 'Ward',
    age: '63',
    email: 'robertcharlesward@yahoo.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Zachary',
    surName: 'Green',
    age: '58',
    email: 'z.r40@yahoo.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Lauren',
    surName: 'Young',
    age: '64',
    email: 'laurenyoung@rocketmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Anthony',
    surName: 'Morris',
    age: '53',
    email: 'anthony_wayne_morris@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Steven',
    surName: 'Cook',
    age: '55',
    email: 'smcook82@ymail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Amanda',
    surName: 'Davis',
    age: '73',
    email: 'adavis90@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Katherine',
    surName: 'Griffin',
    age: '68',
    email: 'katherine_griffin@yahoo.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Jack',
    surName: 'Moore',
    age: '72',
    email: 'j_moore@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Chelsea',
    surName: 'Walker',
    age: '40',
    email: 'c_m_walker@live.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Christina',
    surName: 'Simmons',
    age: '55',
    email: 'christina@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Julian',
    surName: 'Hughes',
    age: '24',
    email: 'j.hughes@yahoo.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Amelia',
    surName: 'Hall',
    age: '50',
    email: 'ameliareneehall84@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Kyle',
    surName: 'Richardson',
    age: '28',
    email: 'kylerichardson@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Timothy',
    surName: 'Lewis',
    age: '42',
    email: 't_r_lewis@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Chelsea',
    surName: 'Perez',
    age: '64',
    email: 'cperez@live.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Aaron',
    surName: 'Wright',
    age: '71',
    email: 'a.wright83@rocketmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Stephen',
    surName: 'Martinez',
    age: '69',
    email: 's.martinez@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Sara',
    surName: 'Powell',
    age: '55',
    email: 'sara_powell@aol.com',
    education: 'Less than high school',
  },
  {
    givenName: 'William',
    surName: 'Foster',
    age: '42',
    email: 'williamfrancisfoster@live.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Charles',
    surName: 'Murphy',
    age: '68',
    email: 'charles_r_murphy@live.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Kyle',
    surName: 'Hayes',
    age: '31',
    email: 'k_w_hayes@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Jack',
    surName: 'Butler',
    age: '57',
    email: 'jackbutler57@rocketmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Chelsea',
    surName: 'Howard',
    age: '35',
    email: 'c_i_howard@yahoo.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Brian',
    surName: 'Russell',
    age: '32',
    email: 'b_a_russell@rocketmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'William',
    surName: 'Carter',
    age: '74',
    email: 'williamcarter@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Isabella',
    surName: 'Thomas',
    age: '20',
    email: 'isabella_thomas1@aol.com',
    education: 'High school diploma or equivalent',
  },
];
